architect:
  - dgroup

readers:
  - "urn:github:1651114"

# @todo #/DEV Generate the pubring.gpg and secring.gpg for rultor.
#  Define a new mvn profile `ossrh-mbox4j` for integration with mvn central.

# @todo #/DEV Configure the deployment to staging environment in order to work with RC
#  https://help.sonatype.com/repomanager2/staging-releases/staging-overview
#  https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment
#  https://nvie.com/posts/a-successful-git-branching-model
#  https://github.com/nvie/gitflow
#  https://gist.github.com/lemiorhan/97b4f827c08aed58a9d8
#  https://github.com/jgitver/jgitver
#  https://danielkummer.github.io/git-flow-cheatsheet/index.html
assets:
  settings.xml: "dgroup/ossrh#settings.xml"
  pubring.gpg:  "dgroup/ossrh#1B112A24-term4j-pubring.gpg"
  secring.gpg:  "dgroup/ossrh#1B112A24-term4j-secring.gpg"

merge:
  env:
      MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - mvn -Pqulice clean package
release:
  script: |
    mvn versions:set "-DnewVersion=$tag"
    git add pom.xml
    git commit -am "$tag"
    mvn -X -V -Dgpg.homedir="$HOME" -P qulice,ossrh-mbox4j -s ../settings.xml clean deploy