#
# Check configuration online:
#   https://lint.travis-ci.org

language: java

sudo: required

cache:
  directories:
    - $HOME/.m2

script:
  - set -e
  - mvn -X -Pqulice clean install
  - mvn -X -Pintegration-tests install -DLL.yandex.user=${EMAIL_USER} -DLL.yandex.pass=${EMAIL_PASS} -DLL.yandex.to.user=${EMAIL_TO}
  - mvn -Psonar sonar:sonar -Dsonar.organization=dgroup-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_LOGIN}

env:
  global:
    - MAVEN_OPTS="-Xmx256m -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -Dorg.slf4j.simpleLogger.showDateTime=true"

jdk:
  - openjdk8

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
